add button component
YanaaShugaylo/MEC pull request #1
Opened 2023-07-27 15:02 UTC by MinaevaEA

Task: https://app.moo.team/WSe857e590/projects/5955/tasks/219988

2023-07-31 12:14 UTC, Gonernyash requested changes

2023-07-31 12:14 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/style/typography/MecTypography.kt
> +    val bold = TextStyle(
зачем

2023-07-31 12:14 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Tags.kt
> +fun Tags(
Можешь ссылку на фигму дать что это такое?

2023-07-31 12:21 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Tags.kt
> +fun Tags(
https://www.figma.com/file/UsvKtx77VZ9h6etOOoez3j/%D0%94%D0%9F%D0%98%D0%B8%D0%A0-Android?type=design&node-id=416-8334&mode=design&t=An9aTKvGMwERy6LQ-0

2023-07-31 12:33 UTC, Gonernyash requested changes

2023-07-31 12:33 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Tags.kt
> +private fun TagBase(
По сути Base как таковой тут не нужен
В кнопках я его делал потому что кнопок много и BaseButton просто хранил в себе те настройки, которые 
применяются вообще для всех кнопок. Делал я это для того, чтобы уменьшить кол-во кода

Компонент Tags в стайлгайде присутствует в единственном числе (просто у него есть 2 состояния), поэтому не вижу смысла в TagBase

Передавать такие аргументы как contentPadding, colors, textStyle и border тоже не имеет смысла, так как по сути они никогда изменятся не будут

2023-08-01 12:06 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Tags.kt
> +private fun TagBase(
исправлено!

2023-08-01 12:06 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/style/typography/MecTypography.kt
> +    val bold = TextStyle(
тут тоже исправлено!

2023-08-04 07:33 UTC, Gonernyash approved these changes

2023-08-04 07:43 UTC, merged