add requests
YanaaShugaylo/MEC pull request #5
Opened 2023-08-01 10:12 UTC by MinaevaEA

Task: https://app.moo.team/WSe857e590/projects/5955/tasks/220477

2023-08-01 12:21 UTC, Gonernyash requested changes

2023-08-01 12:21 UTC, Gonernyash commented on app/src/main/res/drawable/icon_edit.xml
@MinaevaEA @YanaaShugaylo @semenmyslin 
Давайте пока не поздно придем к единому неймингу
Все иконки называем ic_"имя иконки"
Все картинки img_"имя картинки"
Желательно, чтобы имя которое вы даете, полноценно дало понять, что же на этом изображении нарисовано
Я уже в проекте вижу что каждый называет как хочет
Если этого не сделать, в будущем будет каша из названий и все поперезапутаемся

2023-08-01 12:21 UTC, Gonernyash commented on app/src/main/res/drawable-xxxhdpi/rectangle_207.png
Наименование rectangle_207 вообще ничего не дает. Когда таких ректанглов станет больше, все кто работают с проектом сойдут с ума, пытаясь найти нужную им картинку

2023-08-01 12:21 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +            .width(238.dp)
Грубая ошибка
Как поведет себя вьюшка если у пользователя экран больше или меньше 238 px?

2023-08-01 12:21 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +            .height(184.dp)
Тоже спорно, судя по фигме достичь такой высоты можно паддингами у контента

2023-08-01 12:21 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +            text = "data",
сюда подставишь аргумент date

2023-08-01 12:21 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                    text = "№ 0101201012",
Сюда аргумент number

2023-08-01 12:21 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                .height(112.dp)
Не надо хардкодить

2023-08-01 12:21 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                    .padding(start = 0.dp, top = 16.dp, end = 0.dp)
start и end по умолчанию 0, смысла их переопределять нет

2023-08-01 12:21 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                        .padding(start = 0.dp, top = 8.dp, end = 0.dp, bottom = 8.dp)
Можно просто:
.padding(vertical = 8.dp)

2023-08-01 12:21 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                        StatusRequests.WARNING -> "Черновик"
Вынести в strings

2023-08-02 07:02 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +            Icon(
Замени на Image 
Icon применяется только для иконок размера 24x24

2023-08-04 05:58 UTC, MinaevaEA commented on app/src/main/res/drawable/icon_edit.xml
прописала правила в README

2023-08-04 05:59 UTC, MinaevaEA commented on app/src/main/res/drawable-xxxhdpi/rectangle_207.png
поправила

2023-08-04 06:03 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +            .width(238.dp)
блин, что то я затупила, исправила

2023-08-04 06:30 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +            .height(184.dp)
поправила

2023-08-04 06:31 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                .height(112.dp)
поправила

2023-08-04 06:31 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                    text = "№ 0101201012",
ну, я так понимаю, это уже когда буду использовать компоненты в экранах

2023-08-04 06:32 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                    .padding(start = 0.dp, top = 16.dp, end = 0.dp)
поправила

2023-08-04 06:32 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                        .padding(start = 0.dp, top = 8.dp, end = 0.dp, bottom = 8.dp)
исправила

2023-08-04 06:37 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +            Icon(
исправила

2023-08-04 07:24 UTC, MinaevaEA commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                        StatusRequests.WARNING -> "Черновик"
исправила

2023-08-04 07:25 UTC, Gonernyash commented on app/src/main/java/pro/midev/mec/presentation/ui/components/Requests.kt
> +                    text = "№ 0101201012",
Даааа, мы же для этого их делаем)

2023-08-04 07:45 UTC, Gonernyash approved these changes

2023-08-04 07:50 UTC, merged